controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee
      - left_ankle
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      left_hip_pitch: {p: 500.0, i: 5.0, d: 30.0}
      left_knee: {p: 800.0, i: 10.0, d: 50.0}
      right_hip_pitch: {p: 500.0, i: 5.0, d: 30.0}
      right_knee: {p: 800.0, i: 10.0, d: 50.0}
      left_hip_yaw: {p: 100.0, i: 1.0, d: 5.0}
      left_hip_roll: {p: 100.0, i: 1.0, d: 5.0}
      left_ankle: {p: 200.0, i: 2.0, d: 10.0}
      right_hip_yaw: {p: 100.0, i: 1.0, d: 5.0}
      right_hip_roll: {p: 100.0, i: 1.0, d: 5.0}
      right_ankle: {p: 200.0, i: 2.0, d: 10.0}